# Generated by Django 5.0 on 2025-03-21 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("A", "Type A (40 passengers)"),
                            ("B", "Type B (30 passengers)"),
                            ("C", "Type C (20 passengers)"),
                        ],
                        max_length=1,
                    ),
                ),
                ("capacity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_phone", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("rental_days", models.IntegerField(default=1)),
                ("end_date", models.DateField()),
                ("pickup", models.CharField(max_length=200)),
                ("destination", models.CharField(max_length=200)),
                ("additional_locations", models.TextField(blank=True, null=True)),
                ("total_distance", models.IntegerField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DP", "Down Payment"),
                            ("PAID", "Paid"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rental.bus"
                    ),
                ),
            ],
        ),
    ]
