# Generated by Django 5.0 on 2025-03-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rental", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "bus_type",
                    models.CharField(
                        choices=[("A", "Type A"), ("B", "Type B"), ("C", "Type C")],
                        max_length=1,
                    ),
                ),
                ("capacity", models.IntegerField()),
            ],
        ),
    ]
