# Generated by Django 5.0 on 2025-03-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0003_location_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
